<div class="jumbotron">
    <h1>Register</h1>
    <?php if ($this->messages): ?>
        <p>
            <?php echo $this->messages[0]; ?>
        </p>
    <?php else: ?>
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('aglbase-register', array('controller' => 'index', 'action' => 'register')));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag();
        ?>
    <?php endif; ?>

</div>